# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bj}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ara T. Howard"]
  s.date = %q{2009-09-23}
  s.default_executable = %q{bj}
  s.email = %q{ara.t.howard@gmail.com}
  s.executables = ["bj"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "HISTORY",
     "LICENSE",
     "README",
     "TODO",
     "VERSION",
     "bin/bj",
     "bj.gemspec",
     "init.rb",
     "install.rb",
     "lib/bj.rb",
     "lib/bj/api.rb",
     "lib/bj/bj.rb",
     "lib/bj/errors.rb",
     "lib/bj/joblist.rb",
     "lib/bj/logger.rb",
     "lib/bj/runner.rb",
     "lib/bj/stdext.rb",
     "lib/bj/table.rb",
     "lib/bj/util.rb",
     "plugin/HISTORY",
     "plugin/README",
     "plugin/Rakefile",
     "plugin/init.rb",
     "plugin/install.rb",
     "plugin/script/bj",
     "plugin/tasks/bj_tasks.rake",
     "plugin/test/bj_test.rb",
     "plugin/uninstall.rb",
     "rakefile",
     "spec/bj.rb",
     "spec/helper.rb",
     "spec/rails_root/README",
     "spec/rails_root/Rakefile",
     "spec/rails_root/app/controllers/application.rb",
     "spec/rails_root/app/helpers/application_helper.rb",
     "spec/rails_root/config/boot.rb",
     "spec/rails_root/config/database.yml",
     "spec/rails_root/config/environment.rb",
     "spec/rails_root/config/environments/development.rb",
     "spec/rails_root/config/environments/production.rb",
     "spec/rails_root/config/environments/test.rb",
     "spec/rails_root/config/initializers/inflections.rb",
     "spec/rails_root/config/initializers/mime_types.rb",
     "spec/rails_root/config/initializers/new_rails_defaults.rb",
     "spec/rails_root/config/routes.rb",
     "spec/rails_root/db/development.sqlite3",
     "spec/rails_root/db/migrate/20080909151517_bj_migration0.rb",
     "spec/rails_root/db/schema.rb",
     "spec/rails_root/doc/README_FOR_APP",
     "spec/rails_root/log/development.log",
     "spec/rails_root/log/production.log",
     "spec/rails_root/log/server.log",
     "spec/rails_root/log/test.log",
     "spec/rails_root/public/404.html",
     "spec/rails_root/public/422.html",
     "spec/rails_root/public/500.html",
     "spec/rails_root/public/dispatch.cgi",
     "spec/rails_root/public/dispatch.fcgi",
     "spec/rails_root/public/dispatch.rb",
     "spec/rails_root/public/favicon.ico",
     "spec/rails_root/public/images/rails.png",
     "spec/rails_root/public/index.html",
     "spec/rails_root/public/javascripts/application.js",
     "spec/rails_root/public/javascripts/controls.js",
     "spec/rails_root/public/javascripts/dragdrop.js",
     "spec/rails_root/public/javascripts/effects.js",
     "spec/rails_root/public/javascripts/prototype.js",
     "spec/rails_root/public/robots.txt",
     "spec/rails_root/script/about",
     "spec/rails_root/script/bj",
     "spec/rails_root/script/console",
     "spec/rails_root/script/dbconsole",
     "spec/rails_root/script/destroy",
     "spec/rails_root/script/generate",
     "spec/rails_root/script/performance/benchmarker",
     "spec/rails_root/script/performance/profiler",
     "spec/rails_root/script/performance/request",
     "spec/rails_root/script/plugin",
     "spec/rails_root/script/process/inspector",
     "spec/rails_root/script/process/reaper",
     "spec/rails_root/script/process/spawner",
     "spec/rails_root/script/runner",
     "spec/rails_root/script/server",
     "spec/rails_root/test/test_helper.rb",
     "todo.yml"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Backgroundjob (Bj) is a brain dead simple, zero admin, background priority queue for Rails.}
  s.test_files = [
    "spec/bj.rb",
     "spec/helper.rb",
     "spec/rails_root/app/controllers/application.rb",
     "spec/rails_root/app/helpers/application_helper.rb",
     "spec/rails_root/config/boot.rb",
     "spec/rails_root/config/environment.rb",
     "spec/rails_root/config/environments/development.rb",
     "spec/rails_root/config/environments/production.rb",
     "spec/rails_root/config/environments/test.rb",
     "spec/rails_root/config/initializers/inflections.rb",
     "spec/rails_root/config/initializers/mime_types.rb",
     "spec/rails_root/config/initializers/new_rails_defaults.rb",
     "spec/rails_root/config/routes.rb",
     "spec/rails_root/db/migrate/20080909151517_bj_migration0.rb",
     "spec/rails_root/db/schema.rb",
     "spec/rails_root/public/dispatch.rb",
     "spec/rails_root/test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<main>, [">= 2.6.0"])
      s.add_runtime_dependency(%q<systemu>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<orderedhash>, [">= 0.0.3"])
    else
      s.add_dependency(%q<main>, [">= 2.6.0"])
      s.add_dependency(%q<systemu>, [">= 1.2.0"])
      s.add_dependency(%q<orderedhash>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<main>, [">= 2.6.0"])
    s.add_dependency(%q<systemu>, [">= 1.2.0"])
    s.add_dependency(%q<orderedhash>, [">= 0.0.3"])
  end
end
